### ISSUE TITLE
[chat] Implement unread messages counter

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/swetrix#295]
Currently the counter is always displayed as 1 if cookie `chatwasopened` is not set (i.e. user never opened the chat or opened and 20 days passed).

If opened, the chat displays the message `Hi, how can I help?`, this is the correct behaviour and the counter 1 should be shown.

But if user writes something into this chat, leaves the page and received a reply later - the counter does not represent newly received messages (i.e. if I reply to the user in the chat 2 times - there won't be a `2` badge displayed).

When chat gets opened - there's a websocket request happening and in case there are unread messages - they're getting received via this WS connection.
I need you to get the unread messages via this connections, and if there are:
1. no messages - display the `re-open chat` button (as it currently does).
<img width="265" alt="Screenshot 2023-02-04 at 21 36 04" src="https://user-images.githubusercontent.com/35810911/216790526-970e1b6c-6474-469d-9aa5-7471e2adb4ed.png">

2. messages - you should display the correct message counter like on the following screenshot
<img width="345" alt="Screenshot 2023-02-04 at 21 36 52" src="https://user-images.githubusercontent.com/35810911/216790561-6f537e9e-a99f-40cb-9df2-d92cbdee6818.png">

**BONUS POINTS** for displaying the correct counter on the 2nd screenshot instead.

**Comment by Pranavvks** [comment]
Hi. Yup, I did follow the environment configuration setup as per your guidelines listed in this webpage : https://docs.swetrix.com/selfhosting/configuring. Upon your comment, I also made a check confirming whether my env configuration matches your spec and there seems to be no problem. 

For your reference I have attached the env configuration :
[Env.txt](https://github.com/Swetrix/roadmap/files/12327420/Env.txt)

**Comment by Pranavvks** [comment]
Thank you! 

 I was able to resolve that issue after making the changes to the env conifguration. However I am still not able to create an account within the dev environment. Nothing happens in the sign up process , it remains in an indefinite cycle. 

Additionaly, there are no error messages within the console.

**Comment by Pranavvks** [comment]
I tried out the steps mentioned, but still not able to log in through the Swetrix FE interface. 

The account gets created via the swagger ui. However using the same account credentials I'm not able to log in. Currently I'm receiving the following error in the frontend : 

ErrorResponse {
  status: 405,
  statusText: 'Method Not Allowed',
  internal: true,
  data: 'Error: You made a POST request to "/v1/auth/login" but did not provide an `action` for route "routes/$", so there is no way to handle the request.',
  error: Error: You made a POST request to "/v1/auth/login" but did not provide an `action` for route "routes/$", so there is no way to handle the request.
      at getInternalRouterError (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:4132:5)
      at submit (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:2816:19)
      at queryImpl (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:2764:28)
      at Object.query (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:2650:24)
      at handleDocumentRequestRR (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/server-runtime/dist/server.js:170:35)
      at requestHandler (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/server-runtime/dist/server.js:61:24)
      at /Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/express/dist/server.js:39:28
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
}

**Comment by Blaumaus** [comment]
> I tried out the steps mentioned, but still not able to log in through the Swetrix FE interface. 
> 
> The account gets created via the swagger ui. However using the same account credentials I'm not able to log in. Currently I'm receiving the following error in the frontend : 
> 
> ErrorResponse {
>   status: 405,
>   statusText: 'Method Not Allowed',
>   internal: true,
>   data: 'Error: You made a POST request to "/v1/auth/login" but did not provide an `action` for route "routes/$", so there is no way to handle the request.',
>   error: Error: You made a POST request to "/v1/auth/login" but did not provide an `action` for route "routes/$", so there is no way to handle the request.
>       at getInternalRouterError (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:4132:5)
>       at submit (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:2816:19)
>       at queryImpl (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:2764:28)
>       at Object.query (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:2650:24)
>       at handleDocumentRequestRR (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/server-runtime/dist/server.js:170:35)
>       at requestHandler (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/server-runtime/dist/server.js:61:24)
>       at /Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/express/dist/server.js:39:28
>       at processTicksAndRejections (node:internal/process/task_queues:96:5)
> }
> 
> 
> 
> 

As I understand it, you're only running dependencies via docker (i.e. just clickhouse and redis), right? If that's the case, you need to set up a link to the Swetrix API (should be something like http://localhost:5005) in the swetrix-fe .env file. This will solve the problem.

I'm not sure if you can run the Swetrix frontend itself via Docker as we recently migrated to Remix and I haven't really tested it with Docker.

So the setup process should look like this:
1. Run the dependency container (docker-compose-dev.yml in swetrix-api)
2. Set up the .env for the API (I see you've already done this) and run it using the `npm run start:dev` command.
3. Set up .env for swetrix-fe and run it with `npm run dev:staging`.

I'll send you my swetrix-fe .env config in the next message.

P.S. If you're curious, this exact issue occurred because the API domain was not set in the swetrix-fe config and all the requests were set to the FE server (Remix actions) instead. But because we don't use Remix actions that much, it returned that 405 error.
