### ISSUE TITLE
bug: Error Events i create, don't appear in the List immediately.

### ISSUE THREAD

**Issue by Alfagun74** [Swetrix/swetrix#329]
### Dupe Check

- [X] I have [searched Swetrix bugs](https://github.com/swetrix/swetrix/issues?q=is%3Aissue+label%3Abug) and there are no duplicates

### Describe the bug

I create an error event using the API and get a 201 CREATED. I open the list and its not there.

### To reproduce

1. Create Event
2. Open List

### Expected behavior

It should be there right after.

### Regression

No, this bug or issue has existed throughout my experience using Swetrix

### Additional context

Timezone Issue?

### Are you using Swetrix cloud version or self-hosted?

I am using Swetrix cloud version (swetrix.com)

### Does this block you from using Swetrix?

No

**Comment by Blaumaus** [comment]
fixed at https://github.com/Swetrix/swetrix/commit/3b79a1fb5558b82a78fb615a2e5ca3e8663373bb
