### ISSUE TITLE
bug: "this hour" comparison doesn't work

### ISSUE THREAD

**Issue by KaelWD** [Swetrix/swetrix#339]
### Dupe Check

- [X] I have [searched Swetrix bugs](https://github.com/swetrix/swetrix/issues?q=is%3Aissue+label%3Abug) and there are no duplicates

### Describe the bug

It either shows no comparison, or compares against per-hour instead of per-minute.

### To reproduce

1. Go to "traffic"
2. Filter by "this hour"
3. Enable compare vs previous period

No comparison is shown.

4. Filter by "last 24 hours"
5. Filter by "this hour" again

Comparison is by hour instead of by minute

### Screenshots

![Screenshot_20241104_170222](https://github.com/user-attachments/assets/d38205fa-b7a9-4fee-8bea-f62024541188)

### Regression

No, this bug or issue has existed throughout my experience using Swetrix

### Are you using Swetrix cloud version or self-hosted?

I am using Swetrix self-hosted version

### Does this block you from using Swetrix?

No

**Comment by Blaumaus** [comment]
resolved at https://github.com/Swetrix/swetrix/commit/0ac1bbffd3983596307ee3ff15ce3390199fc820
