### ISSUE TITLE
bug: performance shows no data if compare is enabled

### ISSUE THREAD

**Issue by KaelWD** [Swetrix/swetrix#340]
### Dupe Check

- [X] I have [searched Swetrix bugs](https://github.com/swetrix/swetrix/issues?q=is%3Aissue+label%3Abug) and there are no duplicates

### Describe the bug

No events yet
No events have been recorded for the specified period, please try a different period.

### To reproduce

1. Go to performance
2. Filter by a period longer than the site has existed, for example 7 days for a site added 3 days ago
3. Enable compare vs previous period

### Expected behavior

Same as the traffic tab, no comparison should be shown but the base data should still be visible

### Regression

No, this bug or issue has existed throughout my experience using Swetrix

### Are you using Swetrix cloud version or self-hosted?

I am using Swetrix self-hosted version

### Does this block you from using Swetrix?

No

**Comment by Blaumaus** [comment]
Fixed at https://github.com/Swetrix/swetrix/commit/35592b0b57a0ab0f23ce435ca887e03a0e8df3fe
