### ISSUE TITLE
rfc: Add IP address to sessions.

### ISSUE THREAD

**Issue by XDark187** [Swetrix/swetrix#346]
### Dupe Check

- [X] I have [searched Swetrix feature requests](https://github.com/swetrix/swetrix/issues?q=label%3Aenhancement) and there are no duplicates

### Describe the solution you'd like?

Add IP addresses to sessions.

### How important is this feature to you?

5 (Can't work without it!)

**Comment by Blaumaus** [comment]
I don't think we will add something like this, as we're committed to being privacy compliant and ethical towards our end users.

But if you wish, you can still do it by utilising our custom events metadata, although I think you would need to ask your users for permission (aka cookie / gdpr banners) to stay compliant
